import Item from "../../assets/5.webp";

export default [
    {
        id: "1",
        name: "Smart Watch",
        stock: 3,
        status: "new",
        price: 5000,
        discountedPrice: 4000,
        warranty: "6 months",
        img: { Item },
    },
    {
        id: "2",
        name: "HeadPhones",
        stock: 30,
        status: "sale",
        price: 2500,
        discountedPrice: 2300,
        warranty: "3 months",
        img: { Item },
    },
    {
        id: "3",
        name: "MX-1234",
        stock: 55,
        price: 2575,
        discountedPrice: 2150,
        warranty: "2 months",
        img: { Item },
    },
    {
        id: "4",
        name: "MY-HP234",
        stock: 200,
        status: "sale",
        price: 4000,
        warranty: "3 months",
        img: { Item },
    },
    {
        id: "5",
        name: "RR-3S56X",
        stock: 53,
        status: "new",
        price: 500,
        discountedPrice: 450,
        img: { Item },
    },
    {
        id: "6",
        name: "HE-456XS",
        stock: 43,
        status: "new",
        price: 1000,
        discountedPrice: 900,
        img: { Item },
    },
    {
        id: "7",
        name: "MY-78SX",
        stock: 30,
        price: 2500,
        discountedPrice: 2100,
        img: { Item },
    },
    {
        id: "8",
        name: "XD-897XX",
        stock: 100,
        status: "sale",
        price: 400,
        img: { Item },
    },
    {
        id: "9",
        name: "WQ-UT78",
        stock: 5,
        status: "hot",
        price: 550,
        discountedPrice: 500,
        img: { Item },
    },
    {
        id: "10",
        name: "DF-#TEC",
        stock: 6,
        status: "new",
        price: 2000,
        discountedPrice: 1800,
        warranty: "6 months",
        img: { Item },
    },
    {
        id: "11",
        name: "XD-56GG",
        stock: "0",
        price: 750,
        img: { Item },
    },
    {
        id: "12",
        name: "TER-3DD",
        stock: 88,
        status: "hot",
        price: 1250,
        discountedPrice: 1100,
        img: { Item },
    },
];
